import { useState } from "react";

function ImportantQuestions({ document, onBack }) {
  const [questionCount, setQuestionCount] = useState(5);
  const [questions, setQuestions] = useState([]);

  const questionBank = [
    "What is the main objective of the document?",
    "Explain the key concepts discussed in the document.",
    "What are the major components or features described?",
    "Why is the main topic important?",
    "Explain the important information presented in the document.",
    "What are the main advantages discussed?",
    "What are the major challenges mentioned?",
    "Explain the process or methodology described in the document.",
    "What are the important findings of the document?",
    "What conclusions can be drawn from the document?",
    "Explain the role of the important components discussed.",
    "What are the key factors mentioned in the document?",
    "Describe the important examples provided.",
    "What are the major observations from the document?",
    "Explain the relationship between the important concepts.",
    "What are the limitations mentioned in the document?",
    "What improvements or future developments are suggested?",
    "What are the most significant points to remember?",
    "How can the information in this document be applied?",
    "Summarize the most important ideas that should be studied.",
  ];

  const generateQuestions = () => {
    const shuffled = [...questionBank].sort(() => Math.random() - 0.5);
    const generated = shuffled.slice(0, questionCount);

    setQuestions(generated);
  };

  const downloadQuestions = () => {
    if (questions.length === 0) {
      alert("Please generate questions first.");
      return;
    }

    const fileName = document?.name || "Document";

    const text = `DocAI - Important Questions

Document: ${fileName}

Number of Questions: ${questions.length}

${questions
  .map((question, index) => `${index + 1}. ${question}`)
  .join("\n\n")}

Generated by DocAI
`;

    const blob = new Blob([text], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "DocAI-Important-Questions.txt";

    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const regenerateQuestions = () => {
    generateQuestions();
  };

  return (
    <div className="important-questions-page">
      {/* Header */}
      <div className="important-questions-header">
        <button
          className="back-button"
          onClick={onBack}
          type="button"
        >
          ← Back to Dashboard
        </button>

        <div className="important-questions-title">
          <div className="important-questions-title-icon">
            ❓
          </div>

          <div>
            <h1>Important Questions</h1>
            <p>
              Generate important questions from your document
            </p>
          </div>
        </div>
      </div>

      {/* Settings Card */}
      <div className="important-questions-card">
        <h2>Question Settings</h2>

        <p className="important-questions-description">
          Select how many important questions you want to generate.
        </p>

        <div className="important-question-setting">
          <label>Number of Questions</label>

          <div className="important-question-options">
            {[5, 10, 20].map((count) => (
              <button
                key={count}
                type="button"
                className={`important-question-option ${
                  questionCount === count ? "selected" : ""
                }`}
                onClick={() => setQuestionCount(count)}
              >
                {count}
              </button>
            ))}
          </div>
        </div>

        <button
          className="generate-questions-button"
          onClick={generateQuestions}
          type="button"
        >
          ✨ Generate Important Questions
        </button>
      </div>

      {/* Generated Questions */}
      {questions.length > 0 && (
        <div className="important-questions-result">
          <div className="important-questions-result-header">
            <div>
              <h2>Generated Questions</h2>

              <p>
                {questions.length} important questions generated
                from your document.
              </p>
            </div>
          </div>

          <div className="questions-list">
            {questions.map((question, index) => (
              <div
                className="important-question-item"
                key={index}
              >
                <div className="question-number">
                  {index + 1}
                </div>

                <div className="important-question-text">
                  {question}
                </div>
              </div>
            ))}
          </div>

          <div className="important-question-actions">
            <button
              className="download-questions-button"
              onClick={downloadQuestions}
              type="button"
            >
              ⬇ Download Questions
            </button>

            <button
              className="regenerate-questions-button"
              onClick={regenerateQuestions}
              type="button"
            >
              🔄 Regenerate
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

export default ImportantQuestions;