import { useState } from "react";

function ImportantDates({ document, onBack }) {
  const [dates, setDates] = useState([]);

  const dateData = [
    {
      date: "15 January 2026",
      event: "Project Submission",
      importance: "High",
    },
    {
      date: "25 January 2026",
      event: "Final Review",
      importance: "High",
    },
    {
      date: "10 February 2026",
      event: "Evaluation",
      importance: "Medium",
    },
    {
      date: "20 February 2026",
      event: "Result Announcement",
      importance: "High",
    },
    {
      date: "5 March 2026",
      event: "Implementation Deadline",
      importance: "Medium",
    },
  ];

  const extractDates = () => {
    setDates(dateData);
  };

  const downloadDates = () => {
    if (dates.length === 0) {
      alert("Please extract important dates first.");
      return;
    }

    const fileName = document?.name || "Document";

    const text = `DocAI - Important Dates

Document: ${fileName}

${dates
  .map(
    (item, index) =>
      `${index + 1}. ${item.date}
Event: ${item.event}
Importance: ${item.importance}`
  )
  .join("\n\n")}

Generated by DocAI
`;

    const blob = new Blob([text], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "DocAI-Important-Dates.txt";

    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const regenerateDates = () => {
    extractDates();
  };

  return (
    <div className="important-dates-page">

      {/* HEADER */}
      <div className="important-dates-header">

        <button
          className="back-button"
          type="button"
          onClick={onBack}
        >
          ← Back to Dashboard
        </button>

        <div className="important-dates-title">

          <div className="important-dates-title-icon">
            🚨
          </div>

          <div>
            <h1>Important Dates</h1>

            <p>
              Extract important dates and events from your document
            </p>
          </div>

        </div>

      </div>


      {/* EXTRACTION CARD */}
      <div className="important-dates-card">

        <h2>Extract Important Dates</h2>

        <p className="important-dates-description">
          Find important dates, deadlines, events and schedules
          mentioned in your document.
        </p>

        <button
          className="extract-dates-button"
          type="button"
          onClick={extractDates}
        >
          ✨ Extract Important Dates
        </button>

      </div>


      {/* RESULTS */}
      {dates.length > 0 && (
        <div className="important-dates-result">

          <div className="important-dates-result-header">

            <div>
              <h2>Important Dates Found</h2>

              <p>
                {dates.length} important dates identified
                from your document.
              </p>
            </div>

          </div>


          {/* TABLE */}
          <div className="dates-table-wrapper">

            <table className="dates-table">

              <thead>
                <tr>
                  <th>#</th>
                  <th>Date</th>
                  <th>Event</th>
                  <th>Importance</th>
                </tr>
              </thead>

              <tbody>

                {dates.map((item, index) => (
                  <tr key={index}>

                    <td>
                      <span className="date-number">
                        {index + 1}
                      </span>
                    </td>

                    <td className="date-value">
                      {item.date}
                    </td>

                    <td>
                      {item.event}
                    </td>

                    <td>
                      <span
                        className={`importance-badge ${item.importance.toLowerCase()}`}
                      >
                        {item.importance}
                      </span>
                    </td>

                  </tr>
                ))}

              </tbody>

            </table>

          </div>


          {/* ACTION BUTTONS */}
          <div className="important-dates-actions">

            <button
              className="download-dates-button"
              type="button"
              onClick={downloadDates}
            >
              ⬇ Download Dates
            </button>

            <button
              className="regenerate-dates-button"
              type="button"
              onClick={regenerateDates}
            >
              🔄 Regenerate
            </button>

          </div>

        </div>
      )}

    </div>
  );
}

export default ImportantDates;