import { useState } from "react";

function Insights({ document, onBack }) {
  const [insights, setInsights] = useState(null);

  const analyzeDocument = () => {
    setInsights({
      pages: 12,
      keyTopics: [
        "Artificial Intelligence",
        "Document Analysis",
        "Machine Learning",
        "Natural Language Processing",
      ],
      keyConcepts: [
        "AI-powered document processing",
        "Automated information extraction",
        "Question answering",
        "Document summarization",
      ],
      complexity: "Medium",
      potentialQuestions: 8,
      importantDates: 5,
    });
  };

  const downloadInsights = () => {
    if (!insights) {
      alert("Please analyze the document first.");
      return;
    }

    const fileName = document?.name || "Document";

    let text = `DocAI - Document Insights\n\n`;
    text += `Document: ${fileName}\n\n`;
    text += `Pages: ${insights.pages}\n`;
    text += `Complexity: ${insights.complexity}\n`;
    text += `Potential Questions: ${insights.potentialQuestions}\n`;
    text += `Important Dates: ${insights.importantDates}\n\n`;

    text += `Key Topics:\n`;

    insights.keyTopics.forEach((topic, index) => {
      text += `${index + 1}. ${topic}\n`;
    });

    text += `\nKey Concepts:\n`;

    insights.keyConcepts.forEach((concept, index) => {
      text += `${index + 1}. ${concept}\n`;
    });

    text += `\nGenerated by DocAI`;

    const blob = new Blob([text], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");

    link.href = url;
    link.download = "DocAI-Insights.txt";

    window.document.body.appendChild(link);

    link.click();

    window.document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const analyzeAgain = () => {
    analyzeDocument();
  };

  return (
    <div className="insights-page">

      {/* HEADER */}

      <div className="insights-header">

        <button
          className="back-button"
          type="button"
          onClick={onBack}
        >
          ← Back to Dashboard
        </button>

        <div className="insights-title">

          <div className="insights-title-icon">
            💡
          </div>

          <div>
            <h1>Document Insights</h1>

            <p>
              Discover key topics, concepts and insights
              from your document
            </p>
          </div>

        </div>

      </div>


      {/* ANALYZE CARD */}

      <div className="insights-card">

        <h2>
          Analyze Document
        </h2>

        <p className="insights-description">
          Get an intelligent overview of your document
          including key topics, concepts, complexity
          and potential questions.
        </p>

        <button
          className="analyze-insights-button"
          type="button"
          onClick={analyzeDocument}
        >
          ✨ Analyze Document
        </button>

      </div>


      {/* RESULTS */}

      {insights && (

        <div className="insights-result">

          <div className="insights-result-header">

            <div>

              <h2>
                Document Analysis
              </h2>

              <p>
                AI-generated insights from{" "}
                <strong>
                  {document?.name || "your document"}
                </strong>
              </p>

            </div>

          </div>


          {/* STATISTICS */}

          <div className="insights-stats">

            <div className="insight-stat-card">

              <div className="insight-stat-icon">
                📄
              </div>

              <div>

                <span>
                  Pages
                </span>

                <strong>
                  {insights.pages}
                </strong>

              </div>

            </div>


            <div className="insight-stat-card">

              <div className="insight-stat-icon">
                🧠
              </div>

              <div>

                <span>
                  Key Topics
                </span>

                <strong>
                  {insights.keyTopics.length}
                </strong>

              </div>

            </div>


            <div className="insight-stat-card">

              <div className="insight-stat-icon">
                ❓
              </div>

              <div>

                <span>
                  Potential Questions
                </span>

                <strong>
                  {insights.potentialQuestions}
                </strong>

              </div>

            </div>


            <div className="insight-stat-card">

              <div className="insight-stat-icon">
                🚨
              </div>

              <div>

                <span>
                  Important Dates
                </span>

                <strong>
                  {insights.importantDates}
                </strong>

              </div>

            </div>

          </div>


          {/* COMPLEXITY */}

          <div className="insight-section">

            <h3>
              📊 Document Complexity
            </h3>

            <div className="complexity-box">

              <span className="complexity-label">
                Overall Complexity
              </span>

              <span className="complexity-badge">
                {insights.complexity}
              </span>

            </div>

          </div>


          {/* KEY TOPICS */}

          <div className="insight-section">

            <h3>
              🎯 Key Topics
            </h3>

            <div className="insight-tags">

              {insights.keyTopics.map(
                (topic, index) => (

                  <span
                    className="insight-tag"
                    key={index}
                  >
                    {topic}
                  </span>

                )
              )}

            </div>

          </div>


          {/* KEY CONCEPTS */}

          <div className="insight-section">

            <h3>
              💡 Key Concepts
            </h3>

            <div className="concept-list">

              {insights.keyConcepts.map(
                (concept, index) => (

                  <div
                    className="concept-item"
                    key={index}
                  >

                    <span className="concept-number">
                      {index + 1}
                    </span>

                    <span className="concept-text">
                      {concept}
                    </span>

                  </div>

                )
              )}

            </div>

          </div>


          {/* ACTION BUTTONS */}

          <div className="insights-actions">

            <button
              className="download-insights-button"
              type="button"
              onClick={downloadInsights}
            >
              ⬇ Download Insights
            </button>

            <button
              className="analyze-again-button"
              type="button"
              onClick={analyzeAgain}
            >
              🔄 Analyze Again
            </button>

          </div>

        </div>

      )}

    </div>
  );
}

export default Insights;