import { useState } from "react";
import { apiRequest } from "./api";

function Tables({ document, onBack }) {
  const [tables, setTables] = useState([]);
  const [loading, setLoading] = useState(false);

  const extractTables = async () => {
    if (!document?.id) {
      alert("Please select a document first.");
      return;
    }

    setLoading(true);
    try {
      const data = await apiRequest(`/api/ai/${document.id}/tables`);
      setTables(Array.isArray(data.tables) ? data.tables.map((table) => ({
        ...table,
        headers: Array.isArray(table.columns) ? table.columns : [],
        rows: Array.isArray(table.rows) ? table.rows : [],
      })) : []);
    } catch (error) {
      alert(error.message);
    } finally {
      setLoading(false);
    }
  };

  const downloadTables = () => {
    if (tables.length === 0) {
      alert("Please extract tables first.");
      return;
    }

    const fileName = document?.name || "Document";

    let text = `DocAI - Extracted Tables\n\n`;
    text += `Document: ${fileName}\n\n`;

    tables.forEach((table, tableIndex) => {
      text += `${tableIndex + 1}. ${table.title}\n\n`;

      text += table.headers.join(" | ");
      text += "\n";

      table.rows.forEach((row) => {
        text += row.join(" | ");
        text += "\n";
      });

      text += "\n";
    });

    text += "Generated by DocAI";

    const blob = new Blob([text], {
      type: "text/plain",
    });

    const url = URL.createObjectURL(blob);

    const link = window.document.createElement("a");
    link.href = url;
    link.download = "DocAI-Extracted-Tables.txt";

    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const regenerateTables = () => {
    extractTables();
  };

  return (
    <div className="tables-page">

      {/* HEADER */}
      <div className="tables-header">

        <button
          className="back-button"
          type="button"
          onClick={onBack}
        >
          ← Back to Dashboard
        </button>

        <div className="tables-title">

          <div className="tables-title-icon">
            📊
          </div>

          <div>
            <h1>Tables</h1>

            <p>
              Extract and understand tables from your document
            </p>
          </div>

        </div>

      </div>


      {/* EXTRACTION CARD */}
      <div className="tables-card">

        <h2>Extract Tables</h2>

        <p className="tables-description">
          Automatically identify and extract structured
          tables from your uploaded document.
        </p>

        <button
          className="extract-tables-button"
          type="button"
          onClick={extractTables}
          disabled={loading}
        >
          {loading ? "Extracting Tables..." : "✨ Extract Tables"}
        </button>

      </div>


      {/* RESULTS */}
      {tables.length > 0 && (
        <div className="tables-result">

          <div className="tables-result-header">

            <div>
              <h2>Extracted Tables</h2>

              <p>
                {tables.length} tables found in your document.
              </p>
            </div>

          </div>


          <div className="tables-list">

            {tables.map((table, tableIndex) => (
              <div
                className="table-container"
                key={tableIndex}
              >

                <div className="table-heading">
                  <span className="table-number">
                    {tableIndex + 1}
                  </span>

                  <h3>
                    {table.title}
                  </h3>
                </div>


                <div className="extracted-table-wrapper">

                  <table className="extracted-table">

                    <thead>
                      <tr>
                        {table.headers.map(
                          (header, index) => (
                            <th key={index}>
                              {header}
                            </th>
                          )
                        )}
                      </tr>
                    </thead>

                    <tbody>

                      {table.rows.map(
                        (row, rowIndex) => (
                          <tr key={rowIndex}>

                            {row.map(
                              (cell, cellIndex) => (
                                <td key={cellIndex}>
                                  {cell}
                                </td>
                              )
                            )}

                          </tr>
                        )
                      )}

                    </tbody>

                  </table>

                </div>

              </div>
            ))}

          </div>


          {/* ACTIONS */}
          <div className="tables-actions">

            <button
              className="download-tables-button"
              type="button"
              onClick={downloadTables}
            >
              ⬇ Download Tables
            </button>

            <button
              className="regenerate-tables-button"
              type="button"
              onClick={regenerateTables}
              disabled={loading}
            >
              🔄 Regenerate
            </button>

          </div>

        </div>
      )}

    </div>
  );
}

export default Tables;